### PR TITLE
Figwheel with react-native-desktop

### PR DESCRIPTION
**Pull request by pablodip**
I tried to integrate figwheel with react-native-desktop, but wasn't totally successful.

The problem is that figwheel normally integrates with the web environment, that is why it works very well with Electron.

I tried to replicate the strategy that uses [re-natal](https://github.com/drapanjanas/re-natal) to integrate figwheel with React Native: using a static main file and `figwheel-bridge.js`. When I run the desktop app the packages transforms some things, but the screen is just blank and figwheel doesn't receive the connection.

@vkjr Could you try to execute it to see if it works for you or to see if you can see any errors?

### CODE REVIEW

**Comment by maxhora** [comment]
Hey @pablodip , have you tried with https://github.com/status-im/re-natal ? "desktop" is separate platform and it's not available in official repo.

**Comment by maxhora** [comment]
P.S. You can use https://github.com/status-im/status-react/tree/develop-desktop as reference to get some ideas, hopefully.

**Comment by pablodip** [comment]
@MaxRis Thanks! I didn't know there was a modified version of re-natal for desktop! :)

I didn't use re-natal itself, but a similar strategy.

I just tried to execute the prod version, that is, without figwheel, and it doesn't work in my local now. And it worked yesterday. That is why I asked @vkjr if he could give it a go to execute this branch, since he knows better than me the environment. :)

Btw, I am getting this error, in case you know about it:

```
JS server already running.
Starting the app...
hostname: illegal option -- I
usage: hostname [-fs] [name-of-host]
void Bridge::setupExecutor() Could not construct connection:  "NetExecutor" constructing default (RemoteServerConnection)
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
qt.network.ssl: Error receiving trust for a CA certificate
```

The packager transformed correctly, with no errors.

**Comment by maxhora** [comment]
Such error hopefully should be fine to ignore it.
Maybe you need to try just to reload JS bundle via developer menu? (CTRL+R and Reload)

**Comment by pablodip** [comment]
Oh, it was that I wasn't running `./ubuntu-server.js`.

**Comment by maxhora** [comment]
if you have launched native app via `react-native run-desktop` it should run `node ubuntu_server.js` automatically in separate terminal tab (at least on Ubuntu)

**Comment by pablodip** [comment]
Yeah, not on OS X, that's probably why, hehe. :)

Okay, I am already getting some error feedback for the figwheel approach. So will try to integrate your modified version of re-natal.

**Comment by vkjr** [comment]
@pablodip, sorry didn't work yesterday so wasn't able to respond. @MaxRis can be more helpful here since he already added figwheel to status-react on desktop.
Should I check this PR in its current state or wait for another changes?
Thanks.

**Comment by pablodip** [comment]
@vkjr I will give it a try with the modified re-natal later today, since there was an error with the current code. So no worries for now, I will let you know. :)

**Comment by pablodip** [comment]
Just made some more progress here, but it isn't working yet.

When running the app the error I get is this:

```
Starting call sendRequest on RCTNetworkingNative... method:GET url: http://localhost:8081/target/desktop/goog/deps.js
goog.require could not find: env.desktop.main
Error: goog.require could not find: env.desktop.main
```

And the screen is stuck with `Waiting for Figwheel to load files`.

And when reloading the app, the error is this:

```
Starting call sendRequest on RCTNetworkingNative... method:GET url: http://localhost:8081/target/desktop/goog/../env/desktop/main.js
ReferenceError: env is not defined
```

And the ubuntu server breaks.

**Comment by maxhora** [comment]
Hey @pablodip , we have similar errors on status-react with lein-figwheel currently. Please try to restart `node ubuntu_server.js` (you should run it in separate terminal, so the window will not close for you on such failure) and try to reload app again from developers menu. Such errors happens every time, but because reloading helps I haven't looked into the reason yet.

**Comment by vkjr** [comment]
@pablodip, in status-react we have few statndard errors that appear when app starts. As @MaxRis mentioned, if error made ubuntu_server.js stop, you need to restart it, than press "cmd+R" and "reload". If ubuntu_server.js shows error but still works, you need only reloading. Sometimes it takes 2-3 reloads until app starts successfully.

**Comment by pablodip** [comment]
@MaxRis @vkjr Thanks! :)

Okay, it is working now when it first loads. (Well, with those 2-3 reloads.)

But it doesn't re-render the root component when reloading code. It requires to reload. At least it is a big step from compiling the whole code all the time. :)

**Comment by pablodip** [comment]
@vkjr Could you give it a try?

1.) Use npm to install the modified re-natal: `npm install`

2.) Say to re-natal to use figwheel: `./node_modules/re-natal/index.js use-figwheel`

3.) Compile with figwheel: `lein desktop-qt-dev-figwheel`

4.) Run the app normally.

**Comment by maxhora** [comment]
@pablodip `develop-desktop` branch of `status-react` "works" with similar issues as you described

**Comment by pablodip** [comment]
@MaxRis Good to know, since I was some time trying to fix it and thought something was failing here. :)) Well, at least they are in the same status now. :)

**Comment by vkjr** [comment]
@pablodip, I tried your branch and on my computer running the app all the time stops on `could not find: env.desktop.main` problem. Reloading doesn't help. Will investigate more.

**Comment by vkjr** [comment]
@pablodip, it seems that production build is broken in current PR. Could you please take a look? (I tried your branch in a new folder with freshly checkouted status-react).

**Comment by pablodip** [comment]
@vkjr 

Will have a look! Just a couple of questions:

* Did you try to use the option `--reset-cache` with `react-native start`?
* When you say that the production build is broken, do you mean to `lein prod-front-qt`?

**Comment by vkjr** [comment]
@pablodip, "yes" is the answer to both questions :)

**Comment by pablodip** [comment]
@vkjr Okay, already fixed the prod build. I tried to set up the dev environment from scratch in a new directory, and I am stuck with the same error as you. So it is working in the other directory, but not in this, and it doesn't have anything different. :S

**Comment by vkjr** [comment]
@pablodip, thanks! Will check the prod. Do I understand correctly that you are continuing on fixing dev to avoid this error?

**Comment by pablodip** [comment]
@vkjr Sure, I wold like to finish this issue, just don't know how to fix that problem, hehe. I have also tried to set the same commit in the repos of `react-native-desktop` and `status-react` to see if things were working differently there, but that didn't help. :S Do you have any idea of what could be causing this?

**Comment by vkjr** [comment]
@pablodip, unfortunately I don't have any idea why it happens :( To be honest, I didn't spend much time on this issue so far.

**Comment by pablodip** [comment]
@vkjr Yeah, and the thing is, is this really worth if status-desktop is going to be inside status-react? Hehe

**Comment by vkjr** [comment]
@pablodip, depends on how much time the fix requires. Probably if we need couple hours (not days) to make it, it would be really nice :)

**Comment by pablodip** [comment]
@vkjr The thing is that the time required is unpredictable, since it is a weird error, hehe. Will try to devote a little more time to see if I can discover anything, but can't promise anything! :))

**Comment by maxhora** [comment]
Closing this PR since alternative changes were merged in separate PR https://github.com/status-im/status-electron/pull/9 based also on changes in this PR. Thanks!

**Pull request closed without merging**
